[package]
name = "waybar-network-applet"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.9.0", features = ["v4_12"] }
gtk4-layer-shell = "0.4.0"
local-ip-address = "0.6.1"
lexopt = "0.3.0"
