name: release

on: workflow_dispatch

env:
  BUILD_VERSION: "0.0.2"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ./build.sh

      - run: ls -l

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: v${{ env.BUILD_VERSION }}
          artifacts: waybar-network-applet,*.deb
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: iliabylich/ppa@notify
        with:
          token: ${{ secrets.PPA_TOKEN }}
